// Copies the repo-root canonical typed ABIs (abis/index.ts) into this package's
// src/generated/abi.ts so the monitor is self-contained and `tsc` (rootDir=src)
// can emit cleanly. Runs in the pre{build,typecheck,test} hooks. Idempotent.
//
// This mirrors app/scripts/sync-shared.mjs — the established repo pattern for
// pulling the FROZEN ABIs into a package that lives under its own rootDir. The
// ABIs are *generated* from abis/index.ts (regenerated by scripts/export-abi.sh),
// never hand-edited here, so we still honour INTEGRATION.md §7 ("import these,
// never hand-write ABIs").
import { existsSync, mkdirSync, copyFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, "..");
// tooling/monitor -> tooling -> repo root
const repoRoot = resolve(pkgRoot, "..", "..");

const abiSrc = join(repoRoot, "abis", "index.ts");
const genDir = join(pkgRoot, "src", "generated");
const abiDest = join(genDir, "abi.ts");

mkdirSync(genDir, { recursive: true });

if (existsSync(abiSrc)) {
  copyFileSync(abiSrc, abiDest);
  console.log("[sync-abi] abis/index.ts -> src/generated/abi.ts");
} else if (!existsSync(abiDest)) {
  // Build-safe fallback so typecheck/test never hard-fail when run standalone
  // (e.g. CI that didn't run export-abi.sh). The shapes match abis/index.ts.
  writeFileSync(
    abiDest,
    "// AUTO-GENERATED fallback — abis/index.ts was missing at sync time.\n" +
      "export const registryAbi = [] as const;\n" +
      "export const distributorAbi = [] as const;\n" +
      "export const actionSourceAbi = [] as const;\n" +
      "export const functionsActionSourceAbi = [] as const;\n" +
      "export const erc20Abi = [] as const;\n",
  );
  console.warn("[sync-abi] abis/index.ts missing — wrote empty fallback abi.ts");
}
