/**
 * Generate `src/generated/abis.ts` from the repo-root `abis/*.json` artifacts.
 *
 * Why a generated module instead of importing `../../../abis/index.ts` directly?
 *  - The SDK ships as a self-contained npm package: `dist/` must not reach
 *    outside the package root, and `rootDir: src` forbids compiling files from
 *    the monorepo `abis/` directory.
 *  - INTEGRATION.md §7 forbids hand-editing ABIs. This script copies the
 *    auto-generated JSON *verbatim* and only wraps each array in `as const` so
 *    viem can infer argument/return/event types. It is the moral equivalent of
 *    `abis/index.ts`, kept in lock-step by re-running `npm run sync-abis`
 *    (which `prebuild`, `typecheck`, and `test` do automatically).
 *
 * The committed `src/generated/abis.ts` lets the package build even if this
 * script is never run; the script keeps it honest against the source of truth.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const abisDir = resolve(here, "../../../abis");
const outFile = resolve(here, "../src/generated/abis.ts");

/** Maps the exported const name in `abis/index.ts` to its JSON file. */
const ABI_FILES: ReadonlyArray<readonly [exportName: string, jsonFile: string]> = [
  ["registryAbi", "CorporateActionRegistry.json"],
  ["distributorAbi", "DividendDistributor.json"],
  ["actionSourceAbi", "AdminActionSource.json"],
  ["functionsActionSourceAbi", "FunctionsActionSource.json"],
  ["erc20Abi", "MockERC20.json"],
];

function loadAbi(jsonFile: string): unknown {
  const raw = readFileSync(resolve(abisDir, jsonFile), "utf8");
  const parsed: unknown = JSON.parse(raw);
  if (!Array.isArray(parsed)) {
    throw new Error(`abi file ${jsonFile} is not a JSON array`);
  }
  return parsed;
}

function main(): void {
  const banner =
    "// AUTO-GENERATED by scripts/sync-abis.ts from repo-root abis/*.json — do not edit by hand.\n" +
    "// Source of truth: docs/INTEGRATION.md §7 + abis/index.ts. Re-run `npm run sync-abis`.\n" +
    "/* eslint-disable */\n\n";

  const blocks = ABI_FILES.map(([exportName, jsonFile]) => {
    const abi = loadAbi(jsonFile);
    // Compact JSON keeps the generated file close to the canonical abis/index.ts.
    return `export const ${exportName} = ${JSON.stringify(abi)} as const;`;
  });

  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, banner + blocks.join("\n\n") + "\n", "utf8");

  // eslint-disable-next-line no-console
  console.log(`sync-abis: wrote ${ABI_FILES.length} ABIs to ${outFile}`);
}

main();
