#!/usr/bin/env bash
# Export contract ABIs from the Foundry build into /abis as both JSON and a typed
# `as const` TypeScript module consumed by the snapshot CLI and the frontend.
# Run after any contract change: `bash scripts/export-abi.sh`
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ABI_DIR="$ROOT/abis"
cd "$ROOT/contracts"

forge build >/dev/null

mkdir -p "$ABI_DIR"

CONTRACTS=(CorporateActionRegistry DividendDistributor AdminActionSource FunctionsActionSource MockERC20)

TS_INDEX="$ABI_DIR/index.ts"
{
  echo "// AUTO-GENERATED by scripts/export-abi.sh — do not edit by hand."
  echo "// Typed (\`as const\`) ABIs for viem/wagmi type inference."
} > "$TS_INDEX"

declare -A VARMAP=(
  [CorporateActionRegistry]=registryAbi
  [DividendDistributor]=distributorAbi
  [AdminActionSource]=actionSourceAbi
  [FunctionsActionSource]=functionsActionSourceAbi
  [MockERC20]=erc20Abi
)

for c in "${CONTRACTS[@]}"; do
  abi="$(forge inspect "$c" abi --json 2>/dev/null || forge inspect "$c" abi)"
  echo "$abi" | jq '.' > "$ABI_DIR/$c.json"
  echo "export const ${VARMAP[$c]} = $(echo "$abi" | jq -c '.') as const;" >> "$TS_INDEX"
  echo "exported $c -> abis/$c.json"
done

echo "wrote $TS_INDEX"
