// Copies the repo-root shared artifacts (typed ABIs + deployment registries) into
// the app so it is self-contained and deployable to Vercel/containers. Runs in the
// pre{dev,build} hooks. Idempotent.
import { existsSync, mkdirSync, readdirSync, readFileSync, copyFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const appRoot = resolve(__dirname, "..");
const repoRoot = resolve(appRoot, "..");

const abiSrc = join(repoRoot, "abis", "index.ts");
const abiDestDir = join(appRoot, "src", "generated");
const abiDest = join(abiDestDir, "abi.ts");

mkdirSync(abiDestDir, { recursive: true });
if (existsSync(abiSrc)) {
  copyFileSync(abiSrc, abiDest);
  console.log("[sync] abi -> src/generated/abi.ts");
} else if (!existsSync(abiDest)) {
  // Build-safe fallback so typecheck never hard-fails when run standalone.
  writeFileSync(
    abiDest,
    "export const registryAbi = [] as const;\nexport const distributorAbi = [] as const;\nexport const actionSourceAbi = [] as const;\nexport const erc20Abi = [] as const;\n",
  );
  console.warn("[sync] abis/index.ts missing — wrote empty fallback abi.ts");
}

const depSrc = join(repoRoot, "deployments");
const depDest = join(appRoot, "public", "deployments");
mkdirSync(depDest, { recursive: true });

const deploymentsByChain = {};
if (existsSync(depSrc)) {
  for (const f of readdirSync(depSrc)) {
    if (!f.endsWith(".json")) continue;
    copyFileSync(join(depSrc, f), join(depDest, f));
    // Address registries are named <chainId>.json; proofs are proofs-*.json.
    if (/^\d+\.json$/.test(f)) {
      try {
        const data = JSON.parse(readFileSync(join(depSrc, f), "utf8"));
        if (data && data.chainId) deploymentsByChain[String(data.chainId)] = data;
      } catch {
        /* ignore malformed */
      }
    }
  }
  console.log("[sync] deployments -> public/deployments/");
}

// Typed, importable deployment map (server + client, no fetch needed for dev).
const genDeployments = join(abiDestDir, "deployments.ts");
writeFileSync(
  genDeployments,
  "// AUTO-GENERATED by scripts/sync-shared.mjs — do not edit by hand.\n" +
    "export type Deployment = {\n  chainId: number; registry: `0x${string}`; distributor: `0x${string}`;\n" +
    "  actionSource: `0x${string}`; usdg: `0x${string}`; tsla: `0x${string}`; amzn: `0x${string}`;\n" +
    "  admin: `0x${string}`; issuer: `0x${string}`; usdgMock?: `0x${string}`;\n};\n" +
    `export const deployments: Record<string, Deployment> = ${JSON.stringify(deploymentsByChain, null, 2)} as const;\n`,
);
console.log("[sync] deployments map -> src/generated/deployments.ts");
